### ISSUE TITLE
Seu readme.md não funciona no modo claro.

### ISSUE THREAD

**Issue by ruisuan** [DarkMod3/DarkMod3#1]
![image](https://github.com/user-attachments/assets/9a057481-e198-4d63-93c1-811c1d59c857)

**Comment by DarkMod3** [comment]
Eu sei mais eu não consigo pensar em um jeito de deixar para os 2 tipos de temas, eu teria que usar as cores pretas para quem tivesse com o tema branco ativo e usar as cores brancas para quando alguem estivesse com o tema preto ativado.
